### ISSUE TITLE
COM Services Java API Failure during mvn install

### ISSUE THREAD

**Issue by wbnns** [esa/nanosat-mo-framework#27]
Hello, I'm a new user trying to get started with the framework. After installing JDK 1.8, and setting the `NMF_HOME` environment variable to root of the cloned repository folder, I get the following error when running `mvn install` in the root of the folder:
```
[INFO] ESA NMF Core MO Services API - COM Services Java API for NMF FAILURE [  0.414 s] 
```
Details:
```
[ERROR] Failed to execute goal int.esa.ccsds.mo:StubGenerator:1.7:generate (default) on project com-nmf: Execution default of goal int.esa.ccsds.mo:StubGenerator:1.7:generate failed: A required class was missing while executing int.
esa.ccsds.mo:StubGenerator:1.7:generate: javax/activation/DataSource
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>int.esa.ccsds.mo:StubGenerator:1.7
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/~/.m2/repository/int/esa/ccsds/mo/StubGenerator/1.7/StubGenerator-1.7.jar
[ERROR] urls[1] = file:/~/.m2/repository/int/esa/ccsds/mo/StubGenerator_Java/1.7/StubGenerator_Java-1.7.jar
[ERROR] urls[2] = file:/~/.m2/repository/int/esa/ccsds/mo/StubGenerator_Lib/1.7/StubGenerator_Lib-1.7.jar
[ERROR] urls[3] = file:/~/.m2/repository/javax/xml/bind/jaxb-api/2.2.12/jaxb-api-2.2.12.jar
[ERROR] urls[4] = file:/~/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.11/jaxb-impl-2.2.11.jar
[ERROR] urls[5] = file:/~/.m2/repository/com/sun/xml/bind/jaxb-core/2.2.11/jaxb-core-2.2.11.jar
[ERROR] urls[6] = file:/~/.m2/repository/org/reflections/reflections/0.9.10/reflections-0.9.10.jar
[ERROR] urls[7] = file:/~/.m2/repository/com/google/guava/guava/15.0/guava-15.0.jar
[ERROR] urls[8] = file:/~/.m2/repository/org/javassist/javassist/3.19.0-GA/javassist-3.19.0-GA.jar
[ERROR] urls[9] = file:/~/.m2/repository/com/google/code/findbugs/annotations/2.0.1/annotations-2.0.1.jar
[ERROR] urls[10] = file:/~/.m2/repository/xml-apis/xml-apis/1.3.04/xml-apis-1.3.04.jar
[ERROR] urls[11] = file:/~/.m2/repository/int/esa/ccsds/mo/StubGenerator_Interfaces/1.7/StubGenerator_Interfaces-1.7.jar
[ERROR] urls[12] = file:/~/.m2/repository/int/esa/ccsds/mo/XML_JAXB/1.7/XML_JAXB-1.7.jar
[ERROR] urls[13] = file:/~/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>int.esa.nmf:reactor:2.0.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR] 
[ERROR] -----------------------------------------------------
```
Was thinking maybe I'm not on the right Java SDK. I'm currently on [Java SE Development Kit 8u251](https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html).

Any ideas? :)

**Comment by CesarCoelho** [comment]
Hi Will,

Java 1.8 works fine as far as I know.
Which branch are you in? master or dev?  (try both)
Also, try with:  mvn clean install

Can you provide the whole log? Save it in a file and put the link here.

:)

**Comment by wbnns** [comment]
@CesarCoelho 

Hello, thanks for the tips and also for trying to help me with this. I tried `mvn clean install` on both `master` and `dev`. Enclosed are the logs for each:
+ [installation_log_master.txt](https://github.com/esa/nanosat-mo-framework/files/4874620/installation_log_master.txt)
+ [installation_log_dev.txt](https://github.com/esa/nanosat-mo-framework/files/4874621/installation_log_dev.txt)

Please let me know if there's anything else I can do to help troubleshoot.

**Comment by CesarCoelho** [comment]
Hi Will,

It seems to be a local problem, I just removed my m2 folder and compile everything just fine (dev branch) on my machine (Java 8 with Windows).
I noticed 3 things: 
1. You are compiling with Java 13.0.2
2. Mac
3. OpenJDK

Your problem seems to be here:
----
[INFO] --- StubGenerator:1.7:generate (default) @ com-nmf ---
[WARNING] The POM for com.sun.xml.bind:jaxb-impl:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for com.sun.xml.bind:jaxb-impl:2.2.11
[ERROR] 'dependencyManagement.dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${tools.jar} @ 

[WARNING] The POM for com.sun.xml.bind:jaxb-core:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for com.sun.xml.bind:jaxb-core:2.2.11
[ERROR] 'dependencyManagement.dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${tools.jar} @ 
------

I know that Java did some changes on JAXB after version 8:
https://www.jesperdj.com/2018/09/30/jaxb-on-java-9-10-11-and-beyond/

That seems to be where your problem is coming from.

My suggestions:
1. Switch from Java 13 to Java 8 and try compiling again. That should solve the problem.
2. If (1) does not work, try in a different machine. I see you are on a Mac... maybe with Windows or Linux? You can run some free Ubuntu inside a VM.

@dmarszk : Did you try compiling the NMF with Java 13? What about on a Mac?

Hope this helps!   :)

**Comment by dmarszk** [comment]
Unfortunately ESA CCSDS MO stack does not support any other version but Java 8. I have the necessary patches in the pipeline but did not have the time to push them out yet. Looks like you have to force Java 8 manually.

**Comment by wbnns** [comment]
@CesarCoelho @dmarszk 

Fixed. Thanks so much for the help!

<img width="1738" alt="Nanosat MO Framework Build Successful" src="https://user-images.githubusercontent.com/1130872/86531141-41751300-beae-11ea-9637-386b61fed11d.png">

Based on Cesar's tips about Java 13 and OpenJDK, it looks like that despite having Java 1.8 installed on my Mac, Maven when installed, [defaults to using the latest Java installation](https://medium.com/@euedofia/fix-default-java-version-on-maven-on-mac-os-x-156cf5930078) which was OpenJDK.

The fix was to change the default Java version used by Maven to 1.8 by navigating to `/usr/local/Cellar/maven/3.6.3_1/bin/` (version may vary) and updating `JAVA_HOME` in `mvn` from:
```
"${JAVA_HOME:-/usr/local/opt/openjdk}"
```
to:
```
"${JAVA_HOME:-$(/usr/libexec/java_home -v 1.8)}"
```
...and then a person on a Mac should be able to run `mvn install` and get started without issue.

I can close this issue now if you all would like, or alternatively, would it be OK to open a pull request with a short note in the [Building](https://github.com/esa/nanosat-mo-framework#building) section of `README.md`, to Mac users who may run into this problem?

**Comment by CesarCoelho** [comment]
Closed!  :)

**Comment by wbnns** [comment]
Thanks again for the help.
